export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/ace-window:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/emacs-async:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/all-the-icons.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/avy:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/company-mode:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/company-box:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/dash.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/doom-modeline:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/emacs-ccls:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/emacs-dashboard:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/emacs-eim:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/emacs-memoize:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/f.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/flycheck:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/ghub:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/ht.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/hydra:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/lsp-mode:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/lsp-ui:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/magit/lisp:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/pages-break-lines:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/pfuture:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/popup-el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/prescient.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/s.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/shrink-path:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/spinner.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/transient:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/treemacs:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/treepy.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/with-editor:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/yasnippet:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/emacs-htmlize:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/ert-runner.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/commander:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/markdown-mode:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/libegit2:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/ansi.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/shut-up:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/dap-mode:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/treemacs/src/elisp:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/bui.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/tree-mode:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/lsp-java:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/emacs-request:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/posframe:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/lsp-treemacs:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/ivy-rich:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/swiper:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/go-mode.el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/rust-mode:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/perspective-el:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/imenu-list:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/emacs-purpose:$(EMACSLOADPATH)
export EMACSLOADPATH :=/home/$(USER)/.emacs.d/modules/tabbar:$(EMACSLOADPATH)

#export PATH:="/home/ppphp/.cask/bin:$(PATH)"

.PHONY: all ace-window all-the-icons all-the-icons-ivy-rich ansi avy cider commander company-box company-lsp company-mode dap-mode doom-modeline editorconfig-emacs emacs-async emacs-ccls emacs-eim emacs-memoize emacs-purpose ert-runner.el f flycheck ghub go-mode hydra imenu-list lsp-mode lsp-ui libegit2 magit multi-term org-mode perspective posframe projectile rust-mode s swiper tabbar transient yasnippet undo-tree

## compile module codes
all: ace-window all-the-icons all-the-icons-ivy-rich ansi avy company-box company-lsp company-mode dap-mode doom-modeline editorconfig-emacs emacs-async emacs-ccls emacs-eim emacs-memoize emacs-purpose f flycheck ghub go-mode hydra imenu-list libegit2 lsp-mode lsp-ui magit multi-term org-mode perspective posframe projectile rust-mode s swiper tabbar transient yasnippet undo-tree

ace-window:
	make compile -C ace-window

all-the-icons:
	cd all-the-icons.el && emacs -Q -batch -f batch-byte-compile *.el

all-the-icons-ivy-rich:
	cd all-the-icons-ivy-rich && emacs -Q -batch -f batch-byte-compile *.el

ansi:
	cd ansi.el && emacs -Q -batch -f batch-byte-compile *.el

avy:
	make compile -C avy

cider:
	cd cider && emacs -Q -batch -f batch-byte-compile *.el

commander:
	cd commander && emacs -Q -batch -f batch-byte-compile commander.el

company-box:
	cd company-box && emacs -Q -batch -f batch-byte-compile *.el

company-lsp:
	cd company-lsp && emacs -Q -batch -f batch-byte-compile *.el

company-mode:
	make compile -C company-mode

doom-modeline:
	cd doom-modeline && emacs -Q -batch -f batch-byte-compile *.el

editorconfig-emacs:
	make -C editorconfig-emacs

emacs-async:
	make -C emacs-async

emacs-ccls:
	cd emacs-ccls && emacs -Q -batch -f batch-byte-compile *.el

emacs-eim:
	make -C emacs-eim

emacs-memoize:
	make -C emacs-memoize

emacs-purpose: 
	cd emacs-purpose && emacs -Q --batch -f batch-byte-compile *.el

ert-runner.el:
	make compile -C ert-runner.el

f:
	cd f.el && emacs -Q --batch -f batch-byte-compile *.el

flycheck:
	cd flycheck && emacs -Q -batch -f batch-byte-compile *.el

ghub:
	make -C ghub

go-mode:
	cd go-mode.el && emacs -Q -batch -f batch-byte-compile *.el

imenu-list:
	cd imenu-list && emacs -Q -batch -f batch-byte-compile *.el

hydra:
	make compile -C hydra

libegit2:
	make -C libegit2

lsp-mode:
	cd lsp-mode && emacs -Q -batch -f batch-byte-compile *.el

dap-mode:
	cd dap-mode && emacs -Q -batch -f batch-byte-compile *.el

lsp-ui:
	cd lsp-ui && emacs -Q -batch -f batch-byte-compile *.el

magit:
	BUILD_MAGIT_LIBGIT=false make -C magit # LIBGIT_DIR=libegit2/build/libgit2 make -C magit

multi-term:
	cd multi-term && emacs -Q --batch -f batch-byte-compile *.el

posframe:
	cd posframe && emacs -Q --batch -f batch-byte-compile *.el

projectile:
	cd projectile && emacs -Q --batch -f batch-byte-compile *.el

s:
	cd s.el && emacs -Q --batch -f batch-byte-compile *.el

swiper:
	cd swiper && emacs -Q --batch -f batch-byte-compile *.el

tabbar:
	cd tabbar && emacs -Q --batch -f batch-byte-compile *.el

org-mode: 
	make -C org-mode

perspective: 
	cd perspective-el && emacs -Q --batch -f batch-byte-compile *.el

rust-mode:
	cd rust-mode && emacs -Q -batch -f batch-byte-compile *.el

transient:
	make -C transient

yasnippet:
	cd  yasnippet; rake

undo-tree:
	cd undo-tree && emacs -Q -batch -f batch-byte-compile *.el
