;;; package --- Summary
;;; Commentary:
;;; Code:
(add-to-list 'load-path "~/.emacs.d/lisp")

(require 'init-deps)
(require 'init-common)
(require 'init-layout)
(require 'init-configfile)
(require 'init-theme)
(require 'init-dashboard)
(require 'init-modeline)
(require 'init-projectile)
(require 'init-magit)
(require 'init-swiper)
(require 'init-company)
(require 'init-yasnippet)
(require 'init-tabbar)
(require 'init-window)
(require 'init-term)
(require 'init-org)
(require 'init-lsp)
(require 'init-evil)
(require 'init-flycheck)
(require 'init-lisp)
(require 'init-makefile)
(require 'init-docker)
(require 'init-hashicorp)
(require 'init-web)
(require 'init-go)
(require 'init-rust)
(require 'init-python)
(require 'init-c)
(require 'init-cpp)
(require 'init-ruby)
(require 'init-dart)
(require 'init-treemacs)
(require 'init-keymap)
(require 'init-socks)

(provide 'init)
;;; init.el ends here
