
* my emacs configure

  I mostly use emacs to do some stuff without database.

  My emacs configure should be consist of some main components, but I am too weak to make it to be true.

* Basic stuff
** subpackage.el(WIP)
   My own package manager to be compatible with use-package, git submodule and my submodules
** posframe
   Make subframe for certain information.
** ivy/swiper
   Search beautiful.
** projectile
   Manage to find my project root, and some help function to search something from the root.
*** binding
    no binding
*** hydra
    projectile-switch-project
*** binding
    C-s swiper-isearch
* Layout Principal
  I am not finding a method to make them work together well.

  A project meta info area like treemacs frame.
  An Editable area like usual buffer.
  An repl are like multi term, debug tools.
  A simple message panel.
  
  Meta info and repl should be dedicated with project.
  
** purpose
   WIP
** perspective
   Work with projectile
** tabbar mode
   Group buffers by a first line plugin. Showing by buffer related project.
*** binding
    C-c <left> tabbar-previous-buffer
    C-c <right> tabbar-next-buffer
*** hydra
    no hydra

* Editing Principal
  Most of editing related should bind a key directly, like cursor, buffer switching.
  There are blurred modes like editing and searching and viewing, because editing is the central but most time is used in viewing.
** yasnippets
   Insert code very fast.
*** binding
    C-c i yas-insert-snippet
** hydra
   Help me when I am viewing codes. There is too much util functions. It shows functions used more frequently than M-x but less frequent than editing.
*** binding
    C-c c hydra-global/body
    M-<space> major-mode-hydra
** multi-cursor
   TBD
* Metainfo Principal
  Metainfo should provide summary of a project. It is important when beginning coding.
** treemacs
   Show file related to project. Tracking editing buffer sometime.
*** binding
    <f8> treemacs
*** hydra
only default hydra in treemacs mode
* REPL Principal
  Provide interactive service other than editing. Making things like serve codes, debugger and cli utility.
** multi-term
   Make a dedicated term.
*** binding
    <f12> multi-term-dedicated-toggle
** magit
   Manage my git actions
* Message Principal
  Provide regulated message, from emacs itself and its plugins, for debugging.
  TBD
