;;; package --- Summary
;;; Commentary:
;;; Code:
(require 'treemacs)
(require 'treemacs-projectile)

(treemacs-follow-mode nil)
(treemacs-git-mode 'deferred)

(setq treemacs-persist-file (f-join user-emacs-directory "local" "treemacs-persist"))

(with-eval-after-load "treemacs"
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.html")  "html" "htm")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.js")  "js")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.ts")  "ts")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.css")  "css")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.scss")  "scss" "sass")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.rb")  "rb" "Vagrantfile" "Gemfile")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.py")  "py")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.awk")  "awk")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.c")  "c")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.h")  "h")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.cpp")  "cpp" "cxx" "cc")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.hpp")  "hpp" "hxx")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.rs")  "rs")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.o")  "o")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.a")  "a")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.s")  "s")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.mk")  "mk")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.m4")  "m4")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.ac")  "ac")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.inp")  "inp")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.in")  "in")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.sh")  "sh")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.bat")  "bat")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.proto")  "proto")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.json")  "json")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.yml")  "yml" "yaml")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.toml")  "toml")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.toml")  "toml")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.tf")  "tf" "nomad" "hcl")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.txt")  "txt")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.log")  "log")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.nix")  "nix")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.go")  "go")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.el")  "el" "elc" "Cask")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file ".gitignore")  "gitignore")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file ".dockerignore")  "dockerignore")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file ".gitmodules")  "gitmodules")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "Dockerfile")  "Dockerfile")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "Makefile")  "Makefile" "GNUMakefile")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "LICENSE")  "LICENSE")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "INSTALL")  "INSTALL")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "MAINTAINERS")  "MAINTAINERS")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "DCO")  "DCO")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "README")  "README")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.org")  "org")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.md")  "md" "markdown")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.texi")  "texi")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.png")  "png")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.svg")  "svg")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.ico")  "ico")
   (treemacs-define-custom-icon (all-the-icons-icon-for-file "name.gz")  "gz")

   (setq treemacs-icon-fallback (concat (all-the-icons-faicon "file-text-o"
         :height 0.9
         :v-adjust -0.05) " "))
   )

(provide 'init-treemacs)
;;; init-treemacs.el ends here
